# **Pandas**

**Library Import**

In [1]:
import pandas as pd

**Series Data**

In [4]:
age = pd.Series([50, 30, 40, 60])

print(age)

0    50
1    30
2    40
3    60
dtype: int64

DataFrame

In [9]:
data= {
    "product":['Laptop','Mobile','Mouse'],
    "Price":[20000, 15000, 200]
}


pd.DataFrame(data)

  product  Price
0  Laptop  20000
1  Mobile  15000
2   Mouse    200

**Data Load**

In [10]:
df = pd.read_csv('/content/SQL_Practice_100_Records.csv')

In [14]:
df.head()

,OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amount
0,1,101,Rahim,Dhaka,201,Laptop,Electronics,2025-01-03,3,50000,150000
1,2,102,Karim,Khulna,202,Mouse,Electronics,2025-01-05,3,1000,3000
2,3,103,Jamil,Dhaka,203,Keyboard,Electronics,2025-01-07,2,1500,3000
3,4,104,Salma,Chattogram,204,Printer,Electronics,2025-01-09,3,15000,45000
4,5,105,Nadia,Rajshahi,205,Monitor,Electronics,2025-01-11,3,12000,36000

In [17]:
print("total_records :", df.shape[0])

total_records : 100

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       100 non-null    int64
 1   CustomerID    100 non-null    int64
 2   CustomerName  100 non-null    object
 3   City          100 non-null    object
 4   ProductID     100 non-null    int64
 5   ProductName   100 non-null    object
 6   Category      100 non-null    object
 7   OrderDate     100 non-null    object
 8   Quantity      100 non-null    int64
 9   UnitPrice     100 non-null    int64
 10  Amount        100 non-null    int64
dtypes: int64(6), object(5)
memory usage: 8.7+ KB

In [20]:
df.describe()

,OrderID,CustomerID,ProductID,Quantity,UnitPrice,Amount
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,105.500000,205.500000,3.080000,11150.000000,34275.000000
std,29.011492,2.886751,2.886751,1.426162,13718.029867,46412.803822
min,1.000000,101.000000,201.000000,1.000000,1000.000000,1000.000000
25%,25.750000,103.000000,203.000000,2.000000,3000.000000,6000.000000
50%,50.500000,105.500000,205.500000,3.000000,7000.000000,18000.000000
75%,75.250000,108.000000,208.000000,4.000000,12000.000000,41250.000000
max,100.000000,110.000000,210.000000,5.000000,50000.000000,250000.000000

In [22]:
df.isnull().sum()

OrderID         0
CustomerID      0
CustomerName    0
City            0
ProductID       0
ProductName     0
Category        0
OrderDate       0
Quantity        0
UnitPrice       0
Amount          0
dtype: int64

In [23]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'ProductID',
       'ProductName', 'Category', 'OrderDate', 'Quantity', 'UnitPrice',
       'Amount'],
      dtype='object')

In [25]:
print("Average_Revenue: ",df['Amount'].mean())

Average_Revenue:  34275.0